In [1]:
from bs4 import BeautifulSoup
import requests

In [16]:
url= 'https://en.wikipedia.org/wiki/List_of_highest-grossing_films'
agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
html= requests.get(url, headers= agent)
print(html)

<Response [200]>

In [47]:
html_page= BeautifulSoup(html.text, 'html')

In [53]:
tables= html_page.findAll('table')

In [57]:
table= tables[0]

In [59]:
table

<table class="wikitable sortable plainrowheaders sticky-header col4right col5center col6center" style="margin:auto; margin:auto;">
<caption>Highest-grossing films<sup class="reference" id="cite_ref-12"><a href="#cite_note-12">[12]</a></sup>
</caption>
<tbody><tr>
<th>Rank
</th>
<th>Peak
</th>
<th>Title
</th>
<th>Worldwide gross
</th>
<th>Year
</th>
<th class="unsortable"><abbr title="References">Ref</abbr>
</th></tr>
<tr>
<td>1
</td>
<td>1
</td>
<th scope="row"><i><a href="/wiki/Avatar_(2009_film)" title="Avatar (2009 film)">Avatar</a></i>
</th>
<td>$2,923,706,026
</td>
<td>2009
</td>
<td><sup class="reference" id="cite_ref-avatar_13-0"><a href="#cite_note-avatar-13">[# 1]</a></sup><sup class="reference" id="cite_ref-avatar_peak_14-0"><a href="#cite_note-avatar_peak-14">[# 2]</a></sup>
</td></tr>
<tr>
<td>2
</td>
<td>1
</td>
<th scope="row"><i><a href="/wiki/Avengers:_Endgame" title="Avengers: Endgame">Avengers: Endgame</a></i>
</th>
<td>$2,797,501,328
</td>
<td data-sort-value="2019-04">2019
</td>
<td><sup class="reference" id="cite_ref-endgame_15-0"><a href="#cite_note-endgame-15">[# 3]</a></sup><sup class="reference" id="cite_ref-endgame_peak_16-0"><a href="#cite_note-endgame_peak-16">[# 4]</a></sup>
</td></tr>
<tr>
<td>3
</td>
<td>3
</td>
<th scope="row"><i><a href="/wiki/Avatar:_The_Way_of_Water" title="Avatar: The Way of Water">Avatar: The Way of Water</a></i>
</th>
<td>$2,320,250,281
</td>
<td data-sort-value="2022-12">2022
</td>
<td><sup class="reference" id="cite_ref-avatar2_17-0"><a href="#cite_note-avatar2-17">[# 5]</a></sup><sup class="reference" id="cite_ref-avatar_2_peak_18-0"><a href="#cite_note-avatar_2_peak-18">[# 6]</a></sup>
</td></tr>
<tr>
<td>4
</td>
<td>1
</td>
<th scope="row"><i><a href="/wiki/Titanic_(1997_film)" title="Titanic (1997 film)">Titanic</a></i>
</th>
<td><sup class="reference plainlinks nourlexpansion" id="ref_Titanic"><a href="#endnote_Titanic">T</a></sup>$2,257,844,554
</td>
<td>1997
</td>
<td><sup class="reference" id="cite_ref-titanic_19-0"><a href="#cite_note-titanic-19">[# 7]</a></sup><sup class="reference" id="cite_ref-titanic_peak_20-0"><a href="#cite_note-titanic_peak-20">[# 8]</a></sup>
</td></tr>
<tr>
<td>5
</td>
<td>3
</td>
<th scope="row"><i><a href="/wiki/Star_Wars:_The_Force_Awakens" title="Star Wars: The Force Awakens">Star Wars: The Force Awakens</a></i>
</th>
<td>$2,068,223,624
</td>
<td data-sort-value="2015-12">2015
</td>
<td><sup class="reference" id="cite_ref-sw7_21-0"><a href="#cite_note-sw7-21">[# 9]</a></sup><sup class="reference" id="cite_ref-sw7_peak_22-0"><a href="#cite_note-sw7_peak-22">[# 10]</a></sup>
</td></tr>
<tr>
<td>6
</td>
<td>4
</td>
<th scope="row"><i><a href="/wiki/Avengers:_Infinity_War" title="Avengers: Infinity War">Avengers: Infinity War</a></i>
</th>
<td>$2,048,359,754
</td>
<td data-sort-value="2018-04">2018
</td>
<td><sup class="reference" id="cite_ref-infinity_war_23-0"><a href="#cite_note-infinity_war-23">[# 11]</a></sup><sup class="reference" id="cite_ref-infinity_war_peak_24-0"><a href="#cite_note-infinity_war_peak-24">[# 12]</a></sup>
</td></tr>
<tr>
<td>7
</td>
<td>6
</td>
<th scope="row"><i><a href="/wiki/Spider-Man:_No_Way_Home" title="Spider-Man: No Way Home">Spider-Man: No Way Home</a></i>
</th>
<td>$1,921,847,111
</td>
<td data-sort-value="2021-12">2021
</td>
<td><sup class="reference" id="cite_ref-nwh_25-0"><a href="#cite_note-nwh-25">[# 13]</a></sup><sup class="reference" id="cite_ref-No_Way_Home_peak_26-0"><a href="#cite_note-No_Way_Home_peak-26">[# 14]</a></sup>
</td></tr>
<tr>
<td>8
</td>
<td>3
</td>
<th scope="row"><i><a href="/wiki/Jurassic_World" title="Jurassic World">Jurassic World</a></i>
</th>
<td>$1,671,537,444
</td>
<td data-sort-value="2015-06-10">2015
</td>
<td><sup class="reference" id="cite_ref-jurassic_world_27-0"><a href="#cite_note-jurassic_world-27">[# 15]</a></sup><sup class="reference" id="cite_ref-jurassic_world_peak_28-0"><a href="#cite_note-jurassic_world_peak-28">[# 16]</a></sup>
</td></tr>
<tr>
<td>9
</td>
<td>7
</td>
<th scope="row"><span data-sort-value="Lion King !"><a href="/wiki/The_Lion_King_(2019_film)" title="The Lion King (2019 film)"><i>The Lion King</i></a></span>
</th>
<td>$1,656,943,394
</td>
<td data-sort-value="2019-07">2019
</td>
<td><sup class="reference" id="cite_ref-29"><a href="#cite_note-29">[# 17]</a></sup><sup class="reference" id="cite_ref-endgame_peak_16-1"><a href="#cite_note-endgame_peak-16">[# 4]</a></sup>
</td></tr>
<tr>
<td>10
</td>
<td>3
</td>
<th scope="row"><span data-sort-value="Avengers !"><a href="/wiki/The_Avengers_(2012_film)" title="The Avengers (2012 film)"><i>The Avengers</i></a></span>
</th>
<td>$1,518,815,515
</td>
<td data-sort-value="2012-04">2012
</td>
<td><sup class="reference" id="cite_ref-avengers_30-0"><a href="#cite_note-avengers-30">[# 18]</a></sup><sup class="reference" id="cite_ref-avengers_peak_31-0"><a href="#cite_note-avengers_peak-31">[# 19]</a></sup>
</td></tr>
<tr>
<td>11
</td>
<td>4
</td>
<th scope="row"><i><a href="/wiki/Furious_7" title="Furious 7">Furious 7</a></i>
</th>
<td>$1,515,341,399
</td>
<td data-sort-value="2015-03">2015
</td>
<td><sup class="reference" id="cite_ref-fast7_32-0"><a href="#cite_note-fast7-32">[# 20]</a></sup><sup class="reference" id="cite_ref-furious_7_peak_33-0"><a href="#cite_note-furious_7_peak-33">[# 21]</a></sup>
</td></tr>
<tr>
<td>12
</td>
<td>11
</td>
<th scope="row"><i><a href="/wiki/Top_Gun:_Maverick" title="Top Gun: Maverick">Top Gun: Maverick</a></i>
</th>
<td>$1,495,696,292
</td>
<td data-sort-value="2022-05">2022
</td>
<td><sup class="reference" id="cite_ref-34"><a href="#cite_note-34">[# 22]</a></sup><sup class="reference" id="cite_ref-Maverick_peak_35-0"><a href="#cite_note-Maverick_peak-35">[# 23]</a></sup>
</td></tr>
<tr>
<td>13
</td>
<td>10
</td>
<th scope="row"><i><a href="/wiki/Frozen_II" title="Frozen II">Frozen II</a></i>
</th>
<td>$1,450,026,933
</td>
<td data-sort-value="2019-11">2019
</td>
<td><sup class="reference" id="cite_ref-36"><a href="#cite_note-36">[# 24]</a></sup><sup class="reference" id="cite_ref-covid_peak_37-0"><a href="#cite_note-covid_peak-37">[# 25]</a></sup>
</td></tr>
<tr>
<td>14
</td>
<td>14
</td>
<th scope="row" style="background:#b6fcb6;"><i><a href="/wiki/Barbie_(film)" title="Barbie (film)">Barbie</a></i> †
</th>
<td>$1,445,638,421
</td>
<td data-sort-value="2023-07">2023
</td>
<td><sup class="reference" id="cite_ref-Barbie_BOM_38-0"><a href="#cite_note-Barbie_BOM-38">[# 26]</a></sup><sup class="reference" id="cite_ref-barbie_peak_39-0"><a href="#cite_note-barbie_peak-39">[# 27]</a></sup>
</td></tr>
<tr>
<td>15
</td>
<td>5
</td>
<th scope="row"><i><a href="/wiki/Avengers:_Age_of_Ultron" title="Avengers: Age of Ultron">Avengers: Age of Ultron</a></i>
</th>
<td>$1,402,809,540
</td>
<td data-sort-value="2015-04">2015
</td>
<td><sup class="reference" id="cite_ref-40"><a href="#cite_note-40">[# 28]</a></sup><sup class="reference" id="cite_ref-furious_7_peak_33-1"><a href="#cite_note-furious_7_peak-33">[# 21]</a></sup>
</td></tr>
<tr>
<td>16
</td>
<td>15
</td>
<th scope="row" style="background:#b6fcb6;"><i><a href="/wiki/The_Super_Mario_Bros._Movie" title="The Super Mario Bros. Movie">The Super Mario Bros. Movie</a></i> †
</th>
<td>$1,361,964,429
</td>
<td data-sort-value="2023-04">2023
</td>
<td><sup class="reference" id="cite_ref-41"><a href="#cite_note-41">[# 29]</a></sup><sup class="reference" id="cite_ref-mario_peak_42-0"><a href="#cite_note-mario_peak-42">[# 30]</a></sup>
</td></tr>
<tr>
<td>17
</td>
<td>9
</td>
<th scope="row"><i><a href="/wiki/Black_Panther_(film)" title="Black Panther (film)">Black Panther</a></i>
</th>
<td>$1,347,280,838
</td>
<td data-sort-value="2018-02">2018
</td>
<td><sup class="reference" id="cite_ref-black_panther_43-0"><a href="#cite_note-black_panther-43">[# 31]</a></sup><sup class="reference" id="cite_ref-44"><a href="#cite_note-44">[# 32]</a></sup>
</td></tr>
<tr>
<td>18
</td>
<td>3
</td>
<th scope="row"><i><a href="/wiki/Harry_Potter_and_the_Deathly_Hallows_%E2%80%93_Part_2" title="Harry Potter and the Deathly Hallows – Part 2">Harry Potter and the Deathly Hallows – Part 2</a></i>
</th>
<td>$1,342,139,727
</td>
<td data-sort-value="2011-07">2011
</td>
<td><sup class="reference" id="cite_ref-hp7.2_45-0"><a href="#cite_note-hp7.2-45">[# 33]</a></sup><sup class="reference" id="cite_ref-HP8_peak_46-0"><a href="#cite_note-HP8_peak-46">[# 34]</a></sup>
</td></tr>
<tr>
<td>19
</td>
<td>9
</td>
<th scope="row"><i><a href="/wiki/Star_Wars:_The_Last_Jedi" title="Star Wars: The Last Jedi">Star Wars: The Last Jedi</a></i>
</th>
<td>$1,332,539,889
</td>
<td data-sort-value="2017-12-13">2017
</td>
<td><sup class="reference" id="cite_ref-sw8_47-0"><a href="#cite_note-sw8-47">[# 35]</a></sup><sup class="reference" id="cite_ref-SW8_peak_48-0"><a href="#cite_note-SW8_peak-48">[# 36]</a></sup>
</td></tr>
<tr>
<td>20
</td>
<td>12
</td>
<th scope="row"><i><a href="/wiki/Jurassic_World:_Fallen_Kingdom" title="Jurassic World: Fallen Kingdom">Jurassic World: Fallen Kingdom</a></i>
</th>
<td>$1,308,473,425
</td>
<td data-sort-value="2018-06">2018
</td>
<td><sup class="reference" id="cite_ref-49"><a href="#cite_note-49">[# 37]</a></sup><sup class="reference" id="cite_ref-infinity_war_peak_24-1"><a href="#cite_note-infinity_war_peak-24">[# 12]</a></sup>
</td></tr>
<tr>
<td>21
</td>
<td>5
</td>
<th scope="row"><i><a href="/wiki/Frozen_(2013_film)" title="Frozen (2013 film)">Frozen</a></i>
</th>
<td><sup class="reference plainlinks nourlexpansion" id="ref_Frozen"><a href="#endnote_Frozen">F</a></sup>$1,290,000,000
</td>
<td data-sort-value="2013-11">2013
</td>
<td><sup class="reference" id="cite_ref-Frozen_50-0"><a href="#cite_note-Frozen-50">[# 38]</a></sup><sup class="reference" id="cite_ref-frozen_peak_51-0"><a href="#cite_note-frozen_peak-51">[# 39]</a></sup>
</td></tr>
<tr>
<td>22
</td>
<td>10
</td>
<th scope="row"><i><a href="/wiki/Beauty_and_the_Beast_(2017_film)" title="Beauty and the Beast (2017 film)">Beauty and the Beast</a></i>
</th>
<td>$1,263,521,126
</td>
<td data-sort-value="2017-03">2017
</td>
<td><sup class="reference" id="cite_ref-beauty_52-0"><a href="#cite_note-beauty-52">[# 40]</a></sup><sup class="reference" id="cite_ref-Beauty_peak_53-0"><a href="#cite_note-Beauty_peak-53">[# 41]</a></sup>
</td></tr>
<tr>
<td>23
</td>
<td>15
</td>
<th scope="row"><i><a href="/wiki/Incredibles_2" title="Incredibles 2">Incredibles 2</a></i>
</th>
<td>$1,242,805,359
</td>
<td data-sort-value="2018-06">2018
</td>
<td><sup class="reference" id="cite_ref-54"><a href="#cite_note-54">[# 42]</a></sup><sup class="reference" id="cite_ref-infinity_war_peak_24-2"><a href="#cite_note-infinity_war_peak-24">[# 12]</a></sup>
</td></tr>
<tr>
<td>24
</td>
<td>11
</td>
<th scope="row"><span data-sort-value="Fate of the Furious !"><i><a href="/wiki/The_Fate_of_the_Furious" title="The Fate of the Furious">The Fate of the Furious</a></i></span>
</th>
<td><sup class="reference plainlinks nourlexpansion" id="ref_Fast_8"><a href="#endnote_Fast_8">F8</a></sup>$1,238,764,765
</td>
<td data-sort-value="2017-04">2017
</td>
<td><sup class="reference" id="cite_ref-55"><a href="#cite_note-55">[# 43]</a></sup><sup class="reference" id="cite_ref-Beauty_peak_53-1"><a href="#cite_note-Beauty_peak-53">[# 41]</a></sup>
</td></tr>
<tr>
<td>25
</td>
<td>5
</td>
<th scope="row"><i><a href="/wiki/Iron_Man_3" title="Iron Man 3">Iron Man 3</a></i>
</th>
<td>$1,214,811,252
</td>
<td data-sort-value="2013-04">2013
</td>
<td><sup class="reference" id="cite_ref-iron_man_3_56-0"><a href="#cite_note-iron_man_3-56">[# 44]</a></sup><sup class="reference" id="cite_ref-iron_man_3_peak_57-0"><a href="#cite_note-iron_man_3_peak-57">[# 45]</a></sup>
</td></tr>
<tr>
<td>26
</td>
<td>10
</td>
<th scope="row"><i><a href="/wiki/Minions_(film)" title="Minions (film)">Minions</a></i>
</th>
<td>$1,159,444,662
</td>
<td data-sort-value="2015-06-17">2015
</td>
<td><sup class="reference" id="cite_ref-58"><a href="#cite_note-58">[# 46]</a></sup><sup class="reference" id="cite_ref-jurassic_world_peak_28-1"><a href="#cite_note-jurassic_world_peak-28">[# 16]</a></sup>
</td></tr>
<tr>
<td>27
</td>
<td>12
</td>
<th scope="row"><i><a href="/wiki/Captain_America:_Civil_War" title="Captain America: Civil War">Captain America: Civil War</a></i>
</th>
<td>$1,153,337,496
</td>
<td data-sort-value="2016-05">2016
</td>
<td><sup class="reference" id="cite_ref-civil_war_59-0"><a href="#cite_note-civil_war-59">[# 47]</a></sup><sup class="reference" id="cite_ref-civil_war_peak_60-0"><a href="#cite_note-civil_war_peak-60">[# 48]</a></sup>
</td></tr>
<tr>
<td>28
</td>
<td>20
</td>
<th scope="row"><i><a href="/wiki/Aquaman_(film)" title="Aquaman (film)">Aquaman</a></i>
</th>
<td>$1,148,528,393
</td>
<td data-sort-value="2018-12">2018
</td>
<td><sup class="reference" id="cite_ref-61"><a href="#cite_note-61">[# 49]</a></sup><sup class="reference" id="cite_ref-infinity_war_peak_24-3"><a href="#cite_note-infinity_war_peak-24">[# 12]</a></sup>
</td></tr>
<tr>
<td>29
</td>
<td>2
</td>
<th scope="row"><span data-sort-value="Lord of the Rings: Return of the King !"><i><a href="/wiki/The_Lord_of_the_Rings:_The_Return_of_the_King" title="The Lord of the Rings: The Return of the King">The Lord of the Rings: The Return of the King</a></i></span>
</th>
<td>$1,147,997,407
</td>
<td data-sort-value="2003-12">2003
</td>
<td><sup class="reference" id="cite_ref-lotr3_62-0"><a href="#cite_note-lotr3-62">[# 50]</a></sup><sup class="reference" id="cite_ref-ROTK_peak_63-0"><a href="#cite_note-ROTK_peak-63">[# 51]</a></sup>
</td></tr>
<tr>
<td>30
</td>
<td>24<sup class="reference plainlinks nourlexpansion" id="ref_LOTR3"><a href="#endnote_LOTR3">RK</a></sup>
</td>
<th scope="row"><i><a href="/wiki/Spider-Man:_Far_From_Home" title="Spider-Man: Far From Home">Spider-Man: Far From Home</a></i>
</th>
<td>$1,131,927,996
</td>
<td data-sort-value="2019-06-28">2019
</td>
<td><sup class="reference" id="cite_ref-64"><a href="#cite_note-64">[# 52]</a></sup><sup class="reference" id="cite_ref-endgame_peak_16-2"><a href="#cite_note-endgame_peak-16">[# 4]</a></sup>
</td></tr>
<tr>
<td>31
</td>
<td>23<sup class="reference plainlinks nourlexpansion" id="ref_LOTR3"><a href="#endnote_LOTR3">RK</a></sup>
</td>
<th scope="row"><i><a href="/wiki/Captain_Marvel_(film)" title="Captain Marvel (film)">Captain Marvel</a></i>
</th>
<td>$1,128,274,794
</td>
<td data-sort-value="2019-03">2019
</td>
<td><sup class="reference" id="cite_ref-captain_marvel_65-0"><a href="#cite_note-captain_marvel-65">[# 53]</a></sup><sup class="reference" id="cite_ref-captain_marvel_peak_66-0"><a href="#cite_note-captain_marvel_peak-66">[# 54]</a></sup>
</td></tr>
<tr>
<td>32
</td>
<td>5<sup class="reference plainlinks nourlexpansion" id="ref_LOTR3"><a href="#endnote_LOTR3">RK</a></sup>
</td>
<th scope="row"><i><a href="/wiki/Transformers:_Dark_of_the_Moon" title="Transformers: Dark of the Moon">Transformers: Dark of the Moon</a></i>
</th>
<td>$1,123,794,079
</td>
<td data-sort-value="2011-06">2011
</td>
<td><sup class="reference" id="cite_ref-67"><a href="#cite_note-67">[# 55]</a></sup><sup class="reference" id="cite_ref-HP8_peak_46-1"><a href="#cite_note-HP8_peak-46">[# 34]</a></sup>
</td></tr>
<tr>
<td>33
</td>
<td>7
</td>
<th scope="row"><i><a href="/wiki/Skyfall" title="Skyfall">Skyfall</a></i>
</th>
<td>$1,108,569,499
</td>
<td data-sort-value="2012-10">2012
</td>
<td><sup class="reference" id="cite_ref-68"><a href="#cite_note-68">[# 56]</a></sup><sup class="reference" id="cite_ref-Skyfall_peak_69-0"><a href="#cite_note-Skyfall_peak-69">[# 57]</a></sup>
</td></tr>
<tr>
<td>34
</td>
<td>10
</td>
<th scope="row"><i><a href="/wiki/Transformers:_Age_of_Extinction" title="Transformers: Age of Extinction">Transformers: Age of Extinction</a></i>
</th>
<td>$1,104,054,072
</td>
<td data-sort-value="2014-06">2014
</td>
<td><sup class="reference" id="cite_ref-transformers_70-0"><a href="#cite_note-transformers-70">[# 58]</a></sup><sup class="reference" id="cite_ref-Transformers_4_peak_71-0"><a href="#cite_note-Transformers_4_peak-71">[# 59]</a></sup>
</td></tr>
<tr>
<td>35
</td>
<td>7
</td>
<th scope="row"><span data-sort-value="Dark Knight Rises !"><i><a href="/wiki/The_Dark_Knight_Rises" title="The Dark Knight Rises">The Dark Knight Rises</a></i></span>
</th>
<td>$1,081,169,825
</td>
<td data-sort-value="2012-07">2012
</td>
<td><sup class="reference" id="cite_ref-72"><a href="#cite_note-72">[# 60]</a></sup><sup class="reference" id="cite_ref-Ice_Age_3_peak_73-0"><a href="#cite_note-Ice_Age_3_peak-73">[# 61]</a></sup>
</td></tr>
<tr>
<td>36
</td>
<td>31
</td>
<th scope="row"><i><a href="/wiki/Joker_(2019_film)" title="Joker (2019 film)">Joker</a></i>
</th>
<td>$1,074,458,282
</td>
<td data-sort-value="2019-10">2019
</td>
<td><sup class="reference" id="cite_ref-74"><a href="#cite_note-74">[# 62]</a></sup><sup class="reference" id="cite_ref-covid_peak_37-1"><a href="#cite_note-covid_peak-37">[# 25]</a></sup>
</td></tr>
<tr>
<td>37
</td>
<td>32
</td>
<th scope="row"><i><a href="/wiki/Star_Wars:_The_Rise_of_Skywalker" title="Star Wars: The Rise of Skywalker">Star Wars: The Rise of Skywalker</a></i>
</th>
<td>$1,074,144,248
</td>
<td data-sort-value="2019-12">2019
</td>
<td><sup class="reference" id="cite_ref-75"><a href="#cite_note-75">[# 63]</a></sup><sup class="reference" id="cite_ref-covid_peak_37-2"><a href="#cite_note-covid_peak-37">[# 25]</a></sup>
</td></tr>
<tr>
<td>38
</td>
<td>30
</td>
<th scope="row"><i><a href="/wiki/Toy_Story_4" title="Toy Story 4">Toy Story 4</a></i>
</th>
<td>$1,073,394,593
</td>
<td data-sort-value="2019-06-19">2019
</td>
<td><sup class="reference" id="cite_ref-76"><a href="#cite_note-76">[# 64]</a></sup><sup class="reference" id="cite_ref-endgame_peak_16-3"><a href="#cite_note-endgame_peak-16">[# 4]</a></sup>
</td></tr>
<tr>
<td>39
</td>
<td>4<sup class="reference plainlinks nourlexpansion" id="ref_TS3"><a href="#endnote_TS3">TS3</a></sup>
</td>
<th scope="row"><i><a href="/wiki/Toy_Story_3" title="Toy Story 3">Toy Story 3</a></i>
</th>
<td>$1,066,970,811
</td>
<td data-sort-value="2010-06">2010
</td>
<td><sup class="reference" id="cite_ref-ts3_77-0"><a href="#cite_note-ts3-77">[# 65]</a></sup><sup class="reference" id="cite_ref-toy_story_3_peak_78-0"><a href="#cite_note-toy_story_3_peak-78">[# 66]</a></sup>
</td></tr>
<tr>
<td>40
</td>
<td>3
</td>
<th scope="row"><i><a href="/wiki/Pirates_of_the_Caribbean:_Dead_Man%27s_Chest" title="Pirates of the Caribbean: Dead Man's Chest">Pirates of the Caribbean: Dead Man's Chest</a></i>
</th>
<td>$1,066,179,747
</td>
<td>2006
</td>
<td><sup class="reference" id="cite_ref-potc2_79-0"><a href="#cite_note-potc2-79">[# 67]</a></sup><sup class="reference" id="cite_ref-POTC_2_peak_80-0"><a href="#cite_note-POTC_2_peak-80">[# 68]</a></sup>
</td></tr>
<tr>
<td>41
</td>
<td>20
</td>
<th scope="row"><i><a class="mw-redirect" href="/wiki/Rogue_One:_A_Star_Wars_Story" title="Rogue One: A Star Wars Story">Rogue One: A Star Wars Story</a></i>
</th>
<td>$1,057,420,387
</td>
<td data-sort-value="2016-12">2016
</td>
<td><sup class="reference" id="cite_ref-81"><a href="#cite_note-81">[# 69]</a></sup><sup class="reference" id="cite_ref-rogue_one_peak_82-0"><a href="#cite_note-rogue_one_peak-82">[# 70]</a></sup>
</td></tr>
<tr>
<td>42
</td>
<td>34
</td>
<th scope="row"><i><a href="/wiki/Aladdin_(2019_film)" title="Aladdin (2019 film)">Aladdin</a></i>
</th>
<td>$1,050,693,953
</td>
<td data-sort-value="2019-05">2019
</td>
<td><sup class="reference" id="cite_ref-83"><a href="#cite_note-83">[# 71]</a></sup><sup class="reference" id="cite_ref-endgame_peak_16-4"><a href="#cite_note-endgame_peak-16">[# 4]</a></sup>
</td></tr>
<tr>
<td>43
</td>
<td>6
</td>
<th scope="row"><i><a href="/wiki/Pirates_of_the_Caribbean:_On_Stranger_Tides" title="Pirates of the Caribbean: On Stranger Tides">Pirates of the Caribbean: On Stranger Tides</a></i>
</th>
<td>$1,045,713,802
</td>
<td data-sort-value="2011-05">2011
</td>

In [64]:
headings= table.findAll('tr')[0]

In [91]:
table_headings= []
for heading in headings:
    heading= heading.text.strip()
    if len(heading)>0:
        table_headings.append(heading)
table_headings.remove('Title')
table_headings

['Rank', 'Peak', 'Worldwide gross', 'Year', 'Ref']

In [49]:
page.findAll('th', {'class':'headerSort'})

[]

In [92]:
import numpy as np
import pandas as pd

df= pd.DataFrame(columns= table_headings)
df

Empty DataFrame
Columns: [Rank, Peak, Worldwide gross, Year, Ref]
Index: []

In [93]:
rows= table.findAll('tr')[1:]
for row in rows:
    row_data= [data.text.strip() for data in row.findAll('td')]
    # print((row_data))
    df.loc[len(df)]= row_data
df

   Rank  Peak   Worldwide gross  Year           Ref
0     1     1    $2,923,706,026  2009    [# 1][# 2]
1     2     1    $2,797,501,328  2019    [# 3][# 4]
2     3     3    $2,320,250,281  2022    [# 5][# 6]
3     4     1   T$2,257,844,554  1997    [# 7][# 8]
4     5     3    $2,068,223,624  2015   [# 9][# 10]
5     6     4    $2,048,359,754  2018  [# 11][# 12]
6     7     6    $1,921,847,111  2021  [# 13][# 14]
7     8     3    $1,671,537,444  2015  [# 15][# 16]
8     9     7    $1,656,943,394  2019   [# 17][# 4]
9    10     3    $1,518,815,515  2012  [# 18][# 19]
10   11     4    $1,515,341,399  2015  [# 20][# 21]
11   12    11    $1,495,696,292  2022  [# 22][# 23]
12   13    10    $1,450,026,933  2019  [# 24][# 25]
13   14    14    $1,445,638,421  2023  [# 26][# 27]
14   15     5    $1,402,809,540  2015  [# 28][# 21]
15   16    15    $1,361,964,429  2023  [# 29][# 30]
16   17     9    $1,347,280,838  2018  [# 31][# 32]
17   18     3    $1,342,139,727  2011  [# 33][# 34]
18   19     9    $1,332,539,889  2017  [# 35][# 36]
19   20    12    $1,308,473,425  2018  [# 37][# 12]
20   21     5   F$1,290,000,000  2013  [# 38][# 39]
21   22    10    $1,263,521,126  2017  [# 40][# 41]
22   23    15    $1,242,805,359  2018  [# 42][# 12]
23   24    11  F8$1,238,764,765  2017  [# 43][# 41]
24   25     5    $1,214,811,252  2013  [# 44][# 45]
25   26    10    $1,159,444,662  2015  [# 46][# 16]
26   27    12    $1,153,337,496  2016  [# 47][# 48]
27   28    20    $1,148,528,393  2018  [# 49][# 12]
28   29     2    $1,147,997,407  2003  [# 50][# 51]
29   30  24RK    $1,131,927,996  2019   [# 52][# 4]
30   31  23RK    $1,128,274,794  2019  [# 53][# 54]
31   32   5RK    $1,123,794,079  2011  [# 55][# 34]
32   33     7    $1,108,569,499  2012  [# 56][# 57]
33   34    10    $1,104,054,072  2014  [# 58][# 59]
34   35     7    $1,081,169,825  2012  [# 60][# 61]
35   36    31    $1,074,458,282  2019  [# 62][# 25]
36   37    32    $1,074,144,248  2019  [# 63][# 25]
37   38    30    $1,073,394,593  2019   [# 64][# 4]
38   39  4TS3    $1,066,970,811  2010  [# 65][# 66]
39   40     3    $1,066,179,747  2006  [# 67][# 68]
40   41    20    $1,057,420,387  2016  [# 69][# 70]
41   42    34    $1,050,693,953  2019   [# 71][# 4]
42   43     6    $1,045,713,802  2011  [# 72][# 66]
43   44     1    $1,037,535,230  1993  [# 73][# 74]
44   45    24    $1,034,800,131  2017  [# 75][# 41]
45   46    22    $1,028,570,942  2016  [# 76][# 77]
46   47     2    $1,027,082,707  1999   [# 78][# 8]
47   48     5    $1,025,468,216  2010  [# 79][# 80]
48   49    24    $1,023,784,195  2016  [# 81][# 48]
49   50    14    $1,017,030,651  2012  [# 82][# 83]

In [97]:
titles=[]
for row in rows:
    titles.append(row.find('th').text.strip())

In [99]:
df['Titles']= titles

In [101]:
df.head()

  Rank Peak  Worldwide gross  Year          Ref                        Titles
0    1    1   $2,923,706,026  2009   [# 1][# 2]                        Avatar
1    2    1   $2,797,501,328  2019   [# 3][# 4]             Avengers: Endgame
2    3    3   $2,320,250,281  2022   [# 5][# 6]      Avatar: The Way of Water
3    4    1  T$2,257,844,554  1997   [# 7][# 8]                       Titanic
4    5    3   $2,068,223,624  2015  [# 9][# 10]  Star Wars: The Force Awakens